import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import type { Metadata } from 'next'
import { imageConfigDefault } from 'next/dist/shared/lib/image-config'
import { Inter } from 'next/font/google'
import BootstrapClient from "./components/BootstrapClient";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'DynamicWeb headless',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <BootstrapClient/>
      </body>
    </html>
  )
}
